# Generated by Django 3.2.4 on 2021-07-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.CharField(default='ydggdjh', max_length=660),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh',
            field=models.CharField(default='tfsyhgs', max_length=660),
        ),
    ]
