# Generated by Django 3.2.4 on 2021-07-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210714_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.CharField(max_length=660),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh',
            field=models.CharField(max_length=660),
        ),
    ]
