# Generated by Django 3.2.4 on 2021-07-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210714_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh',
        ),
    ]
